### ISSUE TITLE
断线问题

### ISSUE THREAD

**Issue by Ptestq** [ACFUN-FOSS/acfun-tools#2]
版本:0.1.1 从7.09日开始频繁断线,重登陆后维持的时候也很短,可以加入自动重连的功能吗?
Error: live list error: http client pretend error: pretend error: Status(502)

**Comment by orzogc** [comment]
请用最新版本

**Comment by Ptestq** [comment]
> 请用最新版本

版本:0.1.2 
升级后一直稳定到 7.24 断线重登后维持时间不超过2小时,时区表示不是本地时间吗?
thread 'tokio-runtime-worker' panicked at 'already borrowed: BorrowMutError', /home/orzogc/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/worker.rs:733:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5

**Comment by orzogc** [comment]
这不是网络问题，你另开一个issue
