### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Ptestq** [ACFUN-FOSS/acfun-tools#3]
版本:0.1.2
问题首次出现是 7.24 ,之后试过几次登陆维持时间都很短,且报错原因相同.

thread 'tokio-runtime-worker' panicked at 'already borrowed: BorrowMutError', /home/orzogc/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/worker.rs:733:49
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5

**Comment by orzogc** [comment]
你试试0.1.3版本
