### ISSUE TITLE
http client pretend error

### ISSUE THREAD

**Issue by Ptestq** [ACFUN-FOSS/acfun-tools#4]
version:0.1.3
发生时间:8.13
运行中断报错:
Error: live list error: http client pretend error: pretend error: Failed to execute request
重新登陆报错:
Error: http client pretend error: pretend error: Failed to read response body
顺便把 getting danmaku timeout 的报错也修了吧.

**Comment by orzogc** [comment]
其实这都是网络问题或者A站服务器的问题，登陆失败是因为你的帐号被A站限制了
